/*
 * Customer Locations and Products API of MyEnterprise
 *
 * Reads customer locations and products
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StandardProducts.Attributes;
using StandardProducts.Models;
using Swashbuckle.AspNetCore.Annotations;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using ProblemDetails = StandardProducts.Models.ProblemDetails;

namespace StandardProducts.Controllers {

    public class BillingInvoiceApiController : Controller {
        private readonly IBillingInvoiceController _implementation;

        public BillingInvoiceApiController(IBillingInvoiceController billingInvoiceController) {
            _implementation = billingInvoiceController;
        }
        /// <summary>
        /// Get invoice PDF file by invoice number
        /// </summary>
        /// <remarks>returns file</remarks>
        /// <param name="getBillingInvoiceFileRequest"></param>
        /// <response code="200">An invoice PDF file content.</response>
        /// <response code="400">Bad Request e.g. validation error shows data issues</response>
        /// <response code="415">Non-parseable request/response</response>
        /// <response code="500">Internal server error</response>
        /// <response code="503">Connection failure</response>
        /// <response code="504">External interface timed out</response>
        /// <response code="0">Unexpected error</response>
        [HttpPost]
        [Route("/api/StandardProducts/GetBillingInvoiceFile")]
        [ValidateModelState]
        [SwaggerOperation("GetBillingInvoiceFilePost")]
        [SwaggerResponse(statusCode: 200, type: typeof(BillingInvoiceFileResult), description: "An invoice PDF file content.")]
        [SwaggerResponse(statusCode: 400, type: typeof(ProblemDetails), description: "Bad Request e.g. validation error shows data issues")]
        [SwaggerResponse(statusCode: 415, type: typeof(ProblemDetails), description: "Non-parseable request/response")]
        [SwaggerResponse(statusCode: 500, type: typeof(ProblemDetails), description: "Internal server error")]
        [SwaggerResponse(statusCode: 503, type: typeof(ProblemDetails), description: "Connection failure")]
        [SwaggerResponse(statusCode: 504, type: typeof(ProblemDetails), description: "External interface timed out")]
        [SwaggerResponse(statusCode: 0, type: typeof(ProblemDetails), description: "Unexpected error")]
        public async Task<IActionResult> GetBillingInvoiceFilePost([FromBody]GetBillingInvoiceFileRequest getBillingInvoiceFileRequest) {
            return new ObjectResult(await _implementation.GetBillingInvoiceFilePostAsync(getBillingInvoiceFileRequest));
        }

        /// <summary>
        /// Gets list of invoices
        /// </summary>
        /// <remarks>Gets list of invoices</remarks>
        /// <param name="billingInvoicesAdvancedSearchRequest"></param>
        /// <response code="200">Success</response>
        /// <response code="400">Bad Request e.g. validation error shows data issues</response>
        /// <response code="415">Non-parseable request/response</response>
        /// <response code="500">Internal server error</response>
        /// <response code="503">Connection failure</response>
        /// <response code="504">External interface timed out</response>
        /// <response code="0">Unexpected error</response>
        [HttpPost]
        [Route("/api/StandardProducts/GetBillingInvoicesAdvancedSearch")]
        [ValidateModelState]
        [SwaggerOperation("GetBillingInvoicesAdvancedSearchPost")]
        [SwaggerResponse(statusCode: 200, type: typeof(BillingInvoicesResult), description: "Success")]
        [SwaggerResponse(statusCode: 400, type: typeof(ProblemDetails), description: "Bad Request e.g. validation error shows data issues")]
        [SwaggerResponse(statusCode: 415, type: typeof(ProblemDetails), description: "Non-parseable request/response")]
        [SwaggerResponse(statusCode: 500, type: typeof(ProblemDetails), description: "Internal server error")]
        [SwaggerResponse(statusCode: 503, type: typeof(ProblemDetails), description: "Connection failure")]
        [SwaggerResponse(statusCode: 504, type: typeof(ProblemDetails), description: "External interface timed out")]
        [SwaggerResponse(statusCode: 0, type: typeof(ProblemDetails), description: "Unexpected error")]
        public async Task<IActionResult> GetBillingInvoicesAdvancedSearchPost([FromBody]BillingInvoicesAdvancedSearchRequest billingInvoicesAdvancedSearchRequest) {
            return new ObjectResult(await _implementation.GetBillingInvoicesAdvancedSearchPostAsync(billingInvoicesAdvancedSearchRequest));
        }

        /// <summary>
        /// Returns all searchable columns for BillingInvoices.
        /// </summary>
        /// <remarks>The endpoint returns a list of searchable BillingInvoices columns with translation and validators</remarks>
        /// <response code="200">Success</response>
        /// <response code="400">Bad Request e.g. validation error shows data issues</response>
        /// <response code="415">Non-parseable request/response</response>
        /// <response code="500">Internal server error</response>
        /// <response code="503">Connection failure</response>
        /// <response code="504">External interface timed out</response>
        /// <response code="0">Unexpected error</response>
        [HttpPost]
        [Route("/api/StandardProducts/GetBillingInvoicesSearchableColumns")]
        [ValidateModelState]
        [SwaggerOperation("GetBillingInvoicesSearchableColumnsPost")]
        [SwaggerResponse(statusCode: 200, type: typeof(SearchableColumnsResult), description: "Success")]
        [SwaggerResponse(statusCode: 400, type: typeof(ProblemDetails), description: "Bad Request e.g. validation error shows data issues")]
        [SwaggerResponse(statusCode: 415, type: typeof(ProblemDetails), description: "Non-parseable request/response")]
        [SwaggerResponse(statusCode: 500, type: typeof(ProblemDetails), description: "Internal server error")]
        [SwaggerResponse(statusCode: 503, type: typeof(ProblemDetails), description: "Connection failure")]
        [SwaggerResponse(statusCode: 504, type: typeof(ProblemDetails), description: "External interface timed out")]
        [SwaggerResponse(statusCode: 0, type: typeof(ProblemDetails), description: "Unexpected error")]
        public async Task<IActionResult> GetBillingInvoicesSearchableColumnsPost() {
            return new ObjectResult(await _implementation.GetBillingInvoicesSearchableColumnsPostAsync());
        }
    }
}
