/*
 * Customer Locations and Products API of MyEnterprise
 *
 * Reads customer locations and products
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StandardProducts.Attributes;
using StandardProducts.Models;
using Swashbuckle.AspNetCore.Annotations;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using ProblemDetails = StandardProducts.Models.ProblemDetails;

namespace StandardProducts.Controllers {

    public class FirewallApiController : Controller {
        private readonly IFirewallController _implementation;

        public FirewallApiController(IFirewallController firewallController) {
            _implementation = firewallController;
        }
        /// <summary>
        /// list of  A1 Virtual Firewall
        /// </summary>
        /// <remarks>The VirtualFirewallDetails endpoint returns the list of</remarks>
        /// <param name="virtualFirewallListRequest"></param>
        /// <response code="200">Success</response>
        /// <response code="400">Bad Request e.g. validation error shows data issues</response>
        /// <response code="415">Non-parseable request/response</response>
        /// <response code="500">Internal server error</response>
        /// <response code="503">Connection failure</response>
        /// <response code="504">External interface timed out</response>
        /// <response code="0">Unexpected error</response>
        [HttpPost]
        [Route("/api/StandardProducts/GetVirtualFirewallList")]
        [ValidateModelState]
        [SwaggerOperation("GetVirtualFirewallListPost")]
        [SwaggerResponse(statusCode: 200, type: typeof(VirtualFirewallResult), description: "Success")]
        [SwaggerResponse(statusCode: 400, type: typeof(ProblemDetails), description: "Bad Request e.g. validation error shows data issues")]
        [SwaggerResponse(statusCode: 415, type: typeof(ProblemDetails), description: "Non-parseable request/response")]
        [SwaggerResponse(statusCode: 500, type: typeof(ProblemDetails), description: "Internal server error")]
        [SwaggerResponse(statusCode: 503, type: typeof(ProblemDetails), description: "Connection failure")]
        [SwaggerResponse(statusCode: 504, type: typeof(ProblemDetails), description: "External interface timed out")]
        [SwaggerResponse(statusCode: 0, type: typeof(ProblemDetails), description: "Unexpected error")]
        public async Task<IActionResult> GetVirtualFirewallListPost([FromBody]VirtualFirewallListRequest virtualFirewallListRequest) {
            return new ObjectResult(await _implementation.GetVirtualFirewallListPostAsync(virtualFirewallListRequest));
        }

        /// <summary>
        /// Verify WebAc number (does it belongs to the product A1 Virtual Firewall or A1 Business Firewall)
        /// </summary>
        /// <remarks>Verify WebAc number (does it belongs to the product A1 Virtual Firewall or A1 Business Firewall)</remarks>
        /// <param name="validateWebAcNumberRequest"></param>
        /// <response code="200">Success</response>
        /// <response code="400">Bad Request e.g. validation error shows data issues</response>
        /// <response code="415">Non-parseable request/response</response>
        /// <response code="500">Internal server error</response>
        /// <response code="503">Connection failure</response>
        /// <response code="504">External interface timed out</response>
        /// <response code="0">Unexpected error</response>
        [HttpPost]
        [Route("/api/StandardProducts/ValidateWebAcNumber")]
        [ValidateModelState]
        [SwaggerOperation("ValidateWebAcNumberPost")]
        [SwaggerResponse(statusCode: 200, type: typeof(ValidateWebAcNumberResult), description: "Success")]
        [SwaggerResponse(statusCode: 400, type: typeof(ProblemDetails), description: "Bad Request e.g. validation error shows data issues")]
        [SwaggerResponse(statusCode: 415, type: typeof(ProblemDetails), description: "Non-parseable request/response")]
        [SwaggerResponse(statusCode: 500, type: typeof(ProblemDetails), description: "Internal server error")]
        [SwaggerResponse(statusCode: 503, type: typeof(ProblemDetails), description: "Connection failure")]
        [SwaggerResponse(statusCode: 504, type: typeof(ProblemDetails), description: "External interface timed out")]
        [SwaggerResponse(statusCode: 0, type: typeof(ProblemDetails), description: "Unexpected error")]
        public async Task<IActionResult> ValidateWebAcNumberPost([FromBody]ValidateWebAcNumberRequest validateWebAcNumberRequest) {
            return new ObjectResult(await _implementation.ValidateWebAcNumberPostAsync(validateWebAcNumberRequest));
        }
    }
}
