/*
 * Customer Locations and Products API of MyEnterprise
 *
 * Reads customer locations and products
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StandardProducts.Attributes;
using StandardProducts.Models;
using Swashbuckle.AspNetCore.Annotations;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using ProblemDetails = StandardProducts.Models.ProblemDetails;

namespace StandardProducts.Controllers {

    public class LocationsApiController : Controller {
        private readonly ILocationsController _implementation;

        public LocationsApiController(ILocationsController locationsController) {
            _implementation = locationsController;
        }
        /// <summary>
        /// Service to check pending imports
        /// </summary>
        /// <remarks>Service to check pending imports</remarks>
        /// <response code="200">the checking was performed successfully</response>
        /// <response code="400">Bad Request e.g. validation error shows data issues</response>
        /// <response code="415">Non-parseable request/response</response>
        /// <response code="500">Internal server error</response>
        /// <response code="503">Connection failure</response>
        /// <response code="504">External interface timed out</response>
        /// <response code="0">Unexpected error</response>
        [HttpPost]
        [Route("/api/StandardProducts/CheckFullLoadProgress")]
        [ValidateModelState]
        [SwaggerOperation("CheckFullLoadProgressPost")]
        [SwaggerResponse(statusCode: 200, type: typeof(CheckFullLoadProgressResult), description: "the checking was performed successfully")]
        [SwaggerResponse(statusCode: 400, type: typeof(ProblemDetails), description: "Bad Request e.g. validation error shows data issues")]
        [SwaggerResponse(statusCode: 415, type: typeof(ProblemDetails), description: "Non-parseable request/response")]
        [SwaggerResponse(statusCode: 500, type: typeof(ProblemDetails), description: "Internal server error")]
        [SwaggerResponse(statusCode: 503, type: typeof(ProblemDetails), description: "Connection failure")]
        [SwaggerResponse(statusCode: 504, type: typeof(ProblemDetails), description: "External interface timed out")]
        [SwaggerResponse(statusCode: 0, type: typeof(ProblemDetails), description: "Unexpected error")]
        public async Task<IActionResult> CheckFullLoadProgressPost() {
            return new ObjectResult(await _implementation.CheckFullLoadProgressPostAsync());
        }

        /// <summary>
        /// Returns list of product names (level2) for filters
        /// </summary>
        /// <remarks>Returns list of product names (level2) for filters</remarks>
        /// <response code="200">Success</response>
        /// <response code="400">Bad Request e.g. validation error shows data issues</response>
        /// <response code="415">Non-parseable request/response</response>
        /// <response code="500">Internal server error</response>
        /// <response code="503">Connection failure</response>
        /// <response code="504">External interface timed out</response>
        /// <response code="0">Unexpected error</response>
        [HttpPost]
        [Route("/api/StandardProducts/GetProductGroupFilters")]
        [ValidateModelState]
        [SwaggerOperation("GetProductGroupFiltersPost")]
        [SwaggerResponse(statusCode: 200, type: typeof(GetProductGroupFiltersResult), description: "Success")]
        [SwaggerResponse(statusCode: 400, type: typeof(ProblemDetails), description: "Bad Request e.g. validation error shows data issues")]
        [SwaggerResponse(statusCode: 415, type: typeof(ProblemDetails), description: "Non-parseable request/response")]
        [SwaggerResponse(statusCode: 500, type: typeof(ProblemDetails), description: "Internal server error")]
        [SwaggerResponse(statusCode: 503, type: typeof(ProblemDetails), description: "Connection failure")]
        [SwaggerResponse(statusCode: 504, type: typeof(ProblemDetails), description: "External interface timed out")]
        [SwaggerResponse(statusCode: 0, type: typeof(ProblemDetails), description: "Unexpected error")]
        public async Task<IActionResult> GetProductGroupFiltersPost() {
            return new ObjectResult(await _implementation.GetProductGroupFiltersPostAsync());
        }

        /// <summary>
        /// Location for KUMS by LocationId
        /// </summary>
        /// <remarks>The location endpoint returns a location for certain LocationId and customer KUMS number</remarks>
        /// <param name="locationRequest"></param>
        /// <response code="200">Success</response>
        /// <response code="400">Bad Request e.g. validation error shows data issues</response>
        /// <response code="415">Non-parseable request/response</response>
        /// <response code="500">Internal server error</response>
        /// <response code="503">Connection failure</response>
        /// <response code="504">External interface timed out</response>
        /// <response code="0">Unexpected error</response>
        [HttpPost]
        [Route("/api/StandardProducts/Location")]
        [ValidateModelState]
        [SwaggerOperation("LocationPost")]
        [SwaggerResponse(statusCode: 200, type: typeof(Location), description: "Success")]
        [SwaggerResponse(statusCode: 400, type: typeof(ProblemDetails), description: "Bad Request e.g. validation error shows data issues")]
        [SwaggerResponse(statusCode: 415, type: typeof(ProblemDetails), description: "Non-parseable request/response")]
        [SwaggerResponse(statusCode: 500, type: typeof(ProblemDetails), description: "Internal server error")]
        [SwaggerResponse(statusCode: 503, type: typeof(ProblemDetails), description: "Connection failure")]
        [SwaggerResponse(statusCode: 504, type: typeof(ProblemDetails), description: "External interface timed out")]
        [SwaggerResponse(statusCode: 0, type: typeof(ProblemDetails), description: "Unexpected error")]
        public async Task<IActionResult> LocationPost([FromBody]LocationRequest locationRequest) {
            return new ObjectResult(await _implementation.LocationPostAsync(locationRequest));
        }

        /// <summary>
        /// Locations count for KUMS
        /// </summary>
        /// <remarks>The locations count endpoint returns the count of locations for certain customer KUMS number</remarks>
        /// <param name="locationsCountRequest"></param>
        /// <response code="200">Success</response>
        /// <response code="400">Bad Request e.g. validation error shows data issues</response>
        /// <response code="415">Non-parseable request/response</response>
        /// <response code="500">Internal server error</response>
        /// <response code="503">Connection failure</response>
        /// <response code="504">External interface timed out</response>
        /// <response code="0">Unexpected error</response>
        [HttpPost]
        [Route("/api/StandardProducts/LocationsCount")]
        [ValidateModelState]
        [SwaggerOperation("LocationsCountPost")]
        [SwaggerResponse(statusCode: 200, type: typeof(LocationsCountResult), description: "Success")]
        [SwaggerResponse(statusCode: 400, type: typeof(ProblemDetails), description: "Bad Request e.g. validation error shows data issues")]
        [SwaggerResponse(statusCode: 415, type: typeof(ProblemDetails), description: "Non-parseable request/response")]
        [SwaggerResponse(statusCode: 500, type: typeof(ProblemDetails), description: "Internal server error")]
        [SwaggerResponse(statusCode: 503, type: typeof(ProblemDetails), description: "Connection failure")]
        [SwaggerResponse(statusCode: 504, type: typeof(ProblemDetails), description: "External interface timed out")]
        [SwaggerResponse(statusCode: 0, type: typeof(ProblemDetails), description: "Unexpected error")]
        public async Task<IActionResult> LocationsCountPost([FromBody]LocationsCountRequest locationsCountRequest) {
            return new ObjectResult(await _implementation.LocationsCountPostAsync(locationsCountRequest));
        }

        /// <summary>
        /// Locations for WholeSale map
        /// </summary>
        /// <remarks>The locations endpoint returns the list of locations for certain customer KUMS number</remarks>
        /// <param name="locationsWsRequest"></param>
        /// <response code="200">Success</response>
        /// <response code="400">Bad Request e.g. validation error shows data issues</response>
        /// <response code="415">Non-parseable request/response</response>
        /// <response code="500">Internal server error</response>
        /// <response code="503">Connection failure</response>
        /// <response code="504">External interface timed out</response>
        /// <response code="0">Unexpected error</response>
        [HttpPost]
        [Route("/api/StandardProducts/LocationsForMapWs")]
        [ValidateModelState]
        [SwaggerOperation("LocationsForMapWsPost")]
        [SwaggerResponse(statusCode: 200, type: typeof(LocationsWsResult), description: "Success")]
        [SwaggerResponse(statusCode: 400, type: typeof(ProblemDetails), description: "Bad Request e.g. validation error shows data issues")]
        [SwaggerResponse(statusCode: 415, type: typeof(ProblemDetails), description: "Non-parseable request/response")]
        [SwaggerResponse(statusCode: 500, type: typeof(ProblemDetails), description: "Internal server error")]
        [SwaggerResponse(statusCode: 503, type: typeof(ProblemDetails), description: "Connection failure")]
        [SwaggerResponse(statusCode: 504, type: typeof(ProblemDetails), description: "External interface timed out")]
        [SwaggerResponse(statusCode: 0, type: typeof(ProblemDetails), description: "Unexpected error")]
        public async Task<IActionResult> LocationsForMapWsPost([FromBody]LocationsWsRequest locationsWsRequest) {
            return new ObjectResult(await _implementation.LocationsForMapWsPostAsync(locationsWsRequest));
        }

        /// <summary>
        /// Locations for KUMS
        /// </summary>
        /// <remarks>The locations endpoint returns the list of locations for certain customer KUMS number</remarks>
        /// <param name="locationsRequest"></param>
        /// <response code="200">Success</response>
        /// <response code="400">Bad Request e.g. validation error shows data issues</response>
        /// <response code="415">Non-parseable request/response</response>
        /// <response code="500">Internal server error</response>
        /// <response code="503">Connection failure</response>
        /// <response code="504">External interface timed out</response>
        /// <response code="0">Unexpected error</response>
        [HttpPost]
        [Route("/api/StandardProducts/Locations")]
        [ValidateModelState]
        [SwaggerOperation("LocationsPost")]
        [SwaggerResponse(statusCode: 200, type: typeof(LocationsResult), description: "Success")]
        [SwaggerResponse(statusCode: 400, type: typeof(ProblemDetails), description: "Bad Request e.g. validation error shows data issues")]
        [SwaggerResponse(statusCode: 415, type: typeof(ProblemDetails), description: "Non-parseable request/response")]
        [SwaggerResponse(statusCode: 500, type: typeof(ProblemDetails), description: "Internal server error")]
        [SwaggerResponse(statusCode: 503, type: typeof(ProblemDetails), description: "Connection failure")]
        [SwaggerResponse(statusCode: 504, type: typeof(ProblemDetails), description: "External interface timed out")]
        [SwaggerResponse(statusCode: 0, type: typeof(ProblemDetails), description: "Unexpected error")]
        public async Task<IActionResult> LocationsPost([FromBody]LocationsRequest locationsRequest) {
            return new ObjectResult(await _implementation.LocationsPostAsync(locationsRequest));
        }

        /// <summary>
        /// Update a location by LocationId with a customer defined name
        /// </summary>
        /// <remarks>Update a location by LocationId with a customer defined name</remarks>
        /// <param name="updateLocationRequest"></param>
        /// <response code="200">the Location was updated successfully</response>
        /// <response code="400">Bad Request e.g. validation error shows data issues</response>
        /// <response code="415">Non-parseable request/response</response>
        /// <response code="500">Internal server error</response>
        /// <response code="503">Connection failure</response>
        /// <response code="504">External interface timed out</response>
        /// <response code="0">Unexpected error</response>
        [HttpPost]
        [Route("/api/StandardProducts/UpdateLocation")]
        [ValidateModelState]
        [SwaggerOperation("UpdateLocationPost")]
        [SwaggerResponse(statusCode: 400, type: typeof(ProblemDetails), description: "Bad Request e.g. validation error shows data issues")]
        [SwaggerResponse(statusCode: 415, type: typeof(ProblemDetails), description: "Non-parseable request/response")]
        [SwaggerResponse(statusCode: 500, type: typeof(ProblemDetails), description: "Internal server error")]
        [SwaggerResponse(statusCode: 503, type: typeof(ProblemDetails), description: "Connection failure")]
        [SwaggerResponse(statusCode: 504, type: typeof(ProblemDetails), description: "External interface timed out")]
        [SwaggerResponse(statusCode: 0, type: typeof(ProblemDetails), description: "Unexpected error")]
        public async Task<IActionResult> UpdateLocationPost([FromBody]UpdateLocationRequest updateLocationRequest) {
            return new ObjectResult(await _implementation.UpdateLocationPostAsync(updateLocationRequest));
        }
    }
}
